       NAMELIST / QMOMK_INPUT_DATA /&

!           USE qmom_kinetic_equation
! start Alberto
        QMOMK, QMOMK_WALL_BC_TYPE, QMOMK_COLLISIONS, QMOMK_COLLISIONS_ORDER, &
         QMOMK_COUPLED, QMOMK_CFL, PRINT_QMOMK_DATA, QMOMK_TYPE
! end Alberto

!
!vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvC
!                                                                      C
!  Module name: QMOMKNAMELIST.INC                                      C
!  Purpose: Variables needed for QMOMK input                           C
!                                                                      C
!                                                                      C
!  Author: Alberto Passalacqua                        Date:            C
!  Reviewer:                                          Date:            C
!                                                                      C
!^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^C
!

