      MODULE dashboard

      LOGICAL            :: WRITE_DASHBOARD
      INTEGER            :: F_DASHBOARD,N_DASHBOARD
      INTEGER            :: NIT_MIN,NIT_MAX
      DOUBLE PRECISION   :: DTMIN,DTMAX
      DOUBLE PRECISION   :: INIT_TIME,SMMIN,SMMAX
      CHARACTER(LEN=40)  :: RUN_STATUS

      END MODULE dashboard

