#!/bin/csh -f
echo
cd driven-cavity
echo "********************************************************************"
echo "driven-cavity"
#
# 1 Processor
#
/bin/rm -r 1proc
mkdir 1proc
cd 1proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=1 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 1 mfix.exe > outrun
#
cd ../
#
# 2 processors
#
/bin/rm -r 2proc
mkdir 2proc
cd 2proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=2 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 2 mfix.exe > outrun
#
cd ../
#
# Diff the results
#
diff 1proc/*.OUT 2proc/*.OUT > outdiff
#
cd ../
#
#***********************************************************************************
# Another case
#***********************************************************************************
cd granular_shear
echo "********************************************************************"
echo "granular_shear"
#
# 1 Processor
#
/bin/rm -r 1proc
mkdir 1proc
cd 1proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=1 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 1 mfix.exe > outrun
#
cd ../
#
# 2 processors
#
/bin/rm -r 2proc
mkdir 2proc
cd 2proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=2 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 2 mfix.exe > outrun
#
cd ../
#
# Diff the results
#
diff 1proc/*.OUT 2proc/*.OUT > outdiff
#
cd ../
#***********************************************************************************
# Another case
#***********************************************************************************
#***********************************************************************************
cd settling-tank
echo "********************************************************************"
echo "settling-tank"
#
# 1 Processor
#
/bin/rm -r 1proc
mkdir 1proc
cd 1proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=1 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 1 mfix.exe > outrun
#
cd ../
#
# 2 processors
#
/bin/rm -r 2proc
mkdir 2proc
cd 2proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=2 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 2 mfix.exe > outrun
#
cd ../
#
# Diff the results
#
diff 1proc/*.OUT 2proc/*.OUT > outdiff
#
cd ../
#***********************************************************************************
# Another case
#***********************************************************************************
#***********************************************************************************
cd simple-2phase
echo "********************************************************************"
echo "simple-2phase"
#
# 1 Processor
#
/bin/rm -r 1proc
mkdir 1proc
cd 1proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=1 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 1 mfix.exe > outrun
#
cd ../
#
# 2 processors
#
/bin/rm -r 2proc
mkdir 2proc
cd 2proc
/bin/cp ../mfix.dat mfix.dat.bak
/bin/rm mfix00*.dat
awk -f ../../script.awk -v ni=1 -v nj=1 -v nk=2 < mfix.dat.bak > mfix.dat
/bin/cp ../../mfix.exe .
mpirun -np 2 mfix.exe > outrun
#
cd ../
#
# Diff the results
#
diff 1proc/*.OUT 2proc/*.OUT > outdiff
#
cd ../
#
#***********************************************************************************
# Testing Over
#***********************************************************************************
echo "Testing is over.  Check outdiff file for differences"
