      SUBROUTINE GET_FILE_STATUS(STATUS_CODE,FILE_NAME)
!
      IMPLICIT NONE
!
      INTEGER         STATUS_CODE
      CHARACTER(LEN=*)   FILE_NAME
      LOGICAL         FILE_EXISTS
!
      INQUIRE (FILE=FILE_NAME,EXIST=FILE_EXISTS)
!
      IF (FILE_EXISTS) THEN
         STATUS_CODE = 1
      ELSE
         STATUS_CODE = 0
      END IF
!
      RETURN
      END
